#!/usr/bin/env python3
"""Regenerate minify.py's reserved-name block -- the globals it must never touch.

Boots a throwaway cart headless in the real TIC-80 binary, has BOOT() trace
every key of _G (the Lua 5.3 standard library plus the TIC-80 API as this build
exposes them), and rewrites the block between `# <reserved>` and
`# </reserved>` in ticpak/minify.py (TIC80_VERSION + TIC80_GLOBALS). The list is
embedded rather than kept in a data file, so minify.py stands alone. Rerun
after upgrading TIC-80 (set $TIC80 to the binary if it isn't found). Docs:
docs/minify.md "Reserved names".

    python scripts/update_reserved.py            # rewrites the block in ticpak/minify.py
    python scripts/update_reserved.py --print    # print the block, change nothing
"""
import os, re, shutil, subprocess, sys, tempfile, textwrap, time

HERE = os.path.dirname(os.path.abspath(__file__))
TARGET = os.path.normpath(os.path.join(HERE, "..", "ticpak", "minify.py"))
sys.path.insert(0, os.path.normpath(os.path.join(HERE, "..")))

PROBE = """-- title: probe
-- script: lua
function BOOT()
  local keys = {}
  for k in pairs(_G) do keys[#keys + 1] = tostring(k) end
  table.sort(keys)
  for _, k in ipairs(keys) do trace("\\nK=" .. k) end
  trace("\\nDONE")
  exit()
end
function TIC() end
"""


def tic80_exe():
    """The same lookup ticpak uses: $TIC80, a tools/ folder above, or PATH."""
    from ticpak.run import tic80_exe as find
    return find()


def run(cmd, cwd, timeout):
    """Capture a headless run's output (same approach as ticpak _run_tty)."""
    if os.name == "nt":
        try:
            done = subprocess.run(cmd, cwd=cwd, capture_output=True, timeout=timeout,
                                  stdin=subprocess.DEVNULL)
            raw = (done.stdout or b"") + (done.stderr or b"")
        except subprocess.TimeoutExpired as exc:
            raw = (exc.stdout or b"") + (exc.stderr or b"")
        return raw.decode(errors="replace").replace("\r", "")
    import pty, select
    master, slave = pty.openpty()
    p = subprocess.Popen(cmd, cwd=cwd, stdout=slave, stderr=slave,
                         stdin=subprocess.DEVNULL, close_fds=True)
    os.close(slave)
    chunks, deadline = [], time.time() + timeout
    while time.time() < deadline:
        if select.select([master], [], [], 0.2)[0]:
            try:
                data = os.read(master, 65536)
            except OSError:
                break
            if not data:
                break
            chunks.append(data)
            if b"DONE" in b"".join(chunks):
                break
        if p.poll() is not None:
            break
    if p.poll() is None:
        p.kill()
        p.wait()
    os.close(master)
    return b"".join(chunks).decode(errors="replace").replace("\r", "")


def main():
    exe = tic80_exe()
    tmp = tempfile.mkdtemp(prefix="update-reserved-")
    try:
        open(os.path.join(tmp, "probe.lua"), "w", encoding="utf-8").write(PROBE)
        out = run([exe, "--fs=.", "--cli", "--skip", "probe.lua"], tmp, 20)
        ver = run([exe, "--fs=.", "--cli", "--skip", "--cmd", "help version & exit"], tmp, 20)
    finally:
        shutil.rmtree(tmp, ignore_errors=True)
    keys = re.findall(r"K=([A-Za-z_][A-Za-z0-9_]*)", out)
    if "DONE" not in out or len(keys) < 30:
        sys.exit("update_reserved: probe did not finish:\n" + out[-2000:])
    m = re.search(r"\b(\d+\.\d+\.\d+\S*(?: Pro)?(?: \([0-9a-f]+\))?)", ver)
    version = m.group(1) if m else "unknown"
    names = sorted(set(keys))
    body = "\n".join(textwrap.wrap(" ".join(names), 100))
    block = ("# <reserved> -- generated by scripts/update_reserved.py; do not edit by hand\n"
             f'TIC80_VERSION = "{version}"\n'
             f'TIC80_GLOBALS = """\n{body}\n""".split()\n'
             "# </reserved>")
    if "--print" in sys.argv:
        print(block)
        return
    src = open(TARGET, encoding="utf-8").read()
    new, n = re.subn(r"# <reserved>.*?# </reserved>", lambda _: block, src, flags=re.S)
    if n != 1:
        sys.exit("update_reserved: no single # <reserved> block in minify.py")
    open(TARGET, "w", encoding="utf-8", newline="\n").write(new)
    print(f"update_reserved: {len(names)} names (TIC-80 {version}) -> {os.path.relpath(TARGET)}"
          + ("" if new != src else " (unchanged)"))


if __name__ == "__main__":
    main()
